### ISSUE TITLE
Incorrect URL is displaying on Browse page when user is selecting another namespace from drop down

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1052]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Click on Browse
4. Select any namespace (e. g /Genera/l ) -- URL will be "https://staging.canonizer.com/browse?namespace=1"
5. Select any namespace (e. g /General/ ) and click on Only My Topics-- URL will be "https://staging.canonizer.com/browse?namespace=1&my=1"
6. Now change namespace (e. g select /organizations/) and observe URL
Note :  Only My Topics is getting deselected

Expected Result : 
URL should be "https://staging.canonizer.com/browse?namespace=7"

Actual Result : 
As of now URL is displaying as "https://staging.canonizer.com/browse?namespace=7&my=1"
Refer attached screenshots
![image](https://user-images.githubusercontent.com/40416610/148037729-e7630b83-c1c7-4c6e-8ce3-d16d47405ba1.png)

**Comment by saniatg** [comment]
@karun0607gautam While testing this issue came across a scenario where the URL is not changing.
I clicked on namespace 'Crypto_currency" which is at 3rd level from drop down, then checked the check box for 'MY TOPIC' , then  I changed the namespace to 'All' the URL WAS NOT CHANGED.
![Screenshot 2022-01-06 at 12 17 29 PM](https://user-images.githubusercontent.com/91254708/148341111-b4dd8ed5-e0a8-4006-b8a3-3b023a2724d0.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 
Verified on Production and is working fine. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
