### ISSUE TITLE
All nick names are not displaying in Nick Name drop down

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1130]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password("User A")
3. Create new topic with "User A"
4. Login with another user "User B" and support "Agreement" camp
5. Again remove support from "Agreement" camp
6. Again click on "Directly Join and Support" 
7. Observe Nick name drop drown

Expected Result : 
User should see all nick names
Actual Result : 
User can see only last selected nick name. Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/152964718-374c02cb-2858-4f02-95a8-f227ac882126.png)

And for other contribution user can see all nick names. Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/152964820-e8d85a05-4a34-4458-bddc-586731b1654f.png)

**Comment by rupalichavan9860** [comment]
Use "nick name 1" and support camps and again remove support. 
Even if user used another nick name "nick name 2" for other contribution(Create camp using "nick name 2") , user can see only previously selected nick name "nick name 1" for supporting camps  .
It should only allow "nick name 2"

**Comment by saniatg** [comment]
@kshitij1326  Not fixed in the case mentioned below:
Steps:

1. User A creates a topic
2. User B navigates to the same topic and click on"Directly Join And Support"
3. All nick names will be visible which is correct
4. Now choose any 1 nick name and submit
5. Remove the support
6. Create a new camp as UserB, all nick names will be seen which is correct, choose 1 and create camp
7. Now click on topic and click on"Directly Join And Support" button

In nick names all nick names will be seen which is incorrect, only that nick name must se auto selected which was used to create camp.
![Screenshot 2022-04-07 at 12 46 43 PM](https://user-images.githubusercontent.com/91254708/162142848-3f64758e-1ee7-466a-9c0b-06cc0f48d86e.png)

**Comment by rupalichavan9860** [comment]
@kshitij1326 last commented issue is still exists .Can you please check again

**Comment by sunnyjindal** [comment]
Kshitij, could you please discuss this in detail with Rupali and sort out the issue?On Thu, Apr 14, 2022 at 4:58pm, Rupali Chavan ***@***.***> ***@***.*** last commented issue is still exists .Can you please check again—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>[
{
***@***.***": "schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "github.com/the-canonizer/canonizer.2.0/issues/1130#issuecomment-1099089957",
"url": "github.com/the-canonizer/canonizer.2.0/issues/1130#issuecomment-1099089957",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "github.com"
}
}
]

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested on production and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
