### ISSUE TITLE
Add the remaining canonized score back to the first camp, so the total of all camps equals canonized score.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1164]
nth camp_score given N camps and canonized value of X.

If (N = 1) then camp_score := X
Else {
	camp_score := X * 1/(2^n)
	If n = 1 then camp_Score += X*1/(2^(N))
}

If I have the above algorithm psuedo code correct, then update the Multi Support Scoring section of the camp statement describing this: https://canonizer.com/topic/53-Canonizer-Algorithms/1-Agreement

In other words, include some psuedo code, or even better a snippet of the actual code used.
It'd also be nice to have a link to the source code file in github that implements this algorithm, all before closing this issue.

Review this English and code snippet in the updated camp statement with @BrentAllsop, @CanonizerJim and Daksh Sharma with the Iffort team.

**Comment by rupalichavan9860** [comment]
@karun0607gautam @BrentAllsop Whenever user added supports to new camp , score is getting added to first camp only. Is this fine ? 

![image](https://user-images.githubusercontent.com/40416610/173357062-621c0954-5cf0-4031-93da-1dc8dad09662.png)

Because according to Brent comment "Yes, the actual value for the 3rd camp will be 0.125, and **this is the value that will be add in the tree, up to the agreement camp score** (don’t want any rounding errors collected into the top score).  But when displayed on the page, it should round up to 0.13."

issue 1 :  camp 3 - score should display 12.5
issue 2 :  newly supported camp score value should get added up to agreement camp(as of now it is getting added to first camp only)

@BrentAllsop Can you please confirm

**Comment by rupalichavan9860** [comment]
@karun0607gautam As discussed in meeting total score should be 1 and need to change score according to new changes so moving this to "to do"

**Comment by rupalichavan9860** [comment]
@karun0607gautam Tested and verified

![image](https://user-images.githubusercontent.com/40416610/174526163-dc8dd791-b3f4-4fdb-97d5-462763bf7eeb.png)

@BrentAllsop Can you please confirm and close

**Comment by BrentAllsop** [comment]
Yes, looks nice so closing this one.

**Comment by rupalichavan9860** [comment]
Verified on production
