### ISSUE TITLE
Create a "Sandy City" Canonizer Algorithm

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1286]
Create a sandy city canonizer algorithm that looks at the person's City field in their address.  If it is Sandy City they get one vote.

Make the comparison as open as possible, case insensitive, and any city value close to Sandy gets 1 vote.

**Comment by rupalichavan9860** [comment]
@BrentAllsop @karun0607gautam I checked with some sandy city addresses but I am facing below issue,
Whenever I select any address I can see city name "Sandy" in field "Address Line 2" and "Salt Lake County" in field "City"
![image](https://user-images.githubusercontent.com/40416610/179898775-9a024a80-1ead-4bd0-abcf-255bc41622a5.png)

Also I checked for Brent's  user 

![image](https://user-images.githubusercontent.com/40416610/179898862-17ca673f-a35f-4269-85a9-4e9f05538f10.png)

And score is working fine when I select "Sandy City" algorithm because may be earlier Brent added city manually .
Now new user can see "Sandy" in field "Address Line 2" according to google address

**Comment by rupalichavan9860** [comment]
Even I tried same address as Brent's address for my test account 
![image](https://user-images.githubusercontent.com/40416610/179899275-dcf74652-798a-49d4-a222-573a8bfab336.png)

and observed score on topic when selecting "Sandy City" algorithm and it is showing 0 because city is "Salt Lake County"

![image](https://user-images.githubusercontent.com/40416610/179899482-6a5e6c2b-1e78-41cb-bd93-1b02eef2771e.png)

**Comment by rupalichavan9860** [comment]
As discussed in meeting I have created separate ticket for above issue #1497 

Once  1497 is fixed I will check "Sandy City" algorithm and close the ticket

**Comment by rupalichavan9860** [comment]
@karun0607gautam @BrentAllsop Tested and working fine .
If user is supporting 2 camps and selected algorithm is "Sandy City" then score is showing like : 
Camp 1 : 0.50
Camp 2 : 0.25

Is this fine @BrentAllsop or it should be same like "One Person One vote"
Camp 1 : 0.75
Camp 2 : 0.25

**Comment by karun0607gautam** [comment]
@rupalichavan9860 , @BrentAllsop Please test this

**Comment by rupalichavan9860** [comment]
Tested and verified. Working fine for me 
@BrentAllsop  Can you please test and close if fine for you

**Comment by rupalichavan9860** [comment]
Verified on production
