### ISSUE TITLE
[Canonizer Forum]  User must be able to update his/her own threads.

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#13]
The user must be able to update threads created or owned by the user

**Comment by akuks** [comment]
This feature will be the part of next release of canonizer.

**Comment by rupalichavan9860** [comment]
@akuks I can't see this feature. Please check and update on this

**Comment by rupalichavan9860** [comment]
@akuks Tested. I found some issues/suggestions below

1. Edit thread should be uniform with create thread page. It should display same fields like 
Title of Thread ( Limit 100 Chars ) * and text box to update Title of Thread(which should be enabled field) and Nick Name drop down (it should display nick name and should be disabled)

2. Page height and width should be uniform . As of now page height and width is displaying smaller than other pages. Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/121059048-a338ae00-c7de-11eb-8cfb-d401dc8894b2.png)

3. Page title should be uniform with create thread page title
 
I would suggest it should be "Edit thread for Camp : Agreement" instead of "Modify title of the thread"

4. After modifying thread title user should redirect to List of All Camp Threads page. As of now user remains on the edit page only

5. Link name to return to list of thread page should be " List of All Camp Threads" instead of "Return to Forum page" like on create thread page 

6. Title of thread is getting updated with blank spaces. Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/121065402-5a84f300-c7e6-11eb-852b-182a6c1c0e93.png)

**Comment by akuks** [comment]
1. Title of the thread would be ok, but Nick Name is not because once created it should always be the same. Otherwise, it will be difficult to track. 
2. I'll check point number 2.
3. It should say what it is for, and it is for modify the thread title, so I think it's ok. We'll discuss it.
4. Redirect is okay, if we are modifying the thread that's in top of the list but if it is somewhere in the 3rd or 4th page then it's difficult to track and not user friendly.
5. Agree with the point.

**Comment by rupalichavan9860** [comment]
@akuks I can't see the changes. Can you please check and confirm ?

**Comment by rupalichavan9860** [comment]
@akuks Also please check for the validations of duplicate thread name. As of now thread name is getting updated with existing thread name , Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/121778515-c84d6800-cbb4-11eb-82b2-5daafb3f7ff7.png)

**Comment by rupalichavan9860** [comment]
@akuks Tested. But still have 1 issue 

Steps to reproduce : 
1. Create any thread with name like "thread 1" and rename with " thread v1" 
2. Create another thread name "thread 2" and rename with "thread 1" 

Expected Result : 
thread name should get renamed

Actual Result : 
It is displaying error message "Thread title must be unique"

**Comment by rupalichavan9860** [comment]
@akuks User is not able to update the thread name with thread name listed under another camp.
It should only check uniqueness for current camp

**Comment by rupalichavan9860** [comment]
@akuks Tested and verified. Working fine now so closing this issue
