### ISSUE TITLE
When select "Include Review" changes are not reflected in the tree 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1314]
Steps:

1. User A creates a topic and camp1, camp2 , supports both camps
2. User B submits change and changes parent of 'camp2' to 'camp1' from "Agreement"
3. User B commits the change and is in review
Actual result: When select " include review" filter the in review changes are not reflected in the tree
Expected result: When applied" Include review" respective changes must be seen in the tree
![Screenshot 2022-04-25 at 12 38 09 PM](https://user-images.githubusercontent.com/91254708/165039409-00ff6d6d-321f-4ed9-ba83-7923a37105a6.png)
![Screenshot 2022-04-25 at 12 38 27 PM](https://user-images.githubusercontent.com/91254708/165039469-54f37b5f-0965-47e6-8815-1b446a6da9ff.png)

**Comment by BrentAllsop** [comment]
Ali pointed out what I had forgotten, that we did this, via consensus, on purpose, to improve performance.

He also proposed we also keep "in review" trees in the mongo db.
This will be good as "in review" is used far more often than any historical as-of value, and for the following reasons:

"in review" mongo trees can be programmed to be automatically removed when they go live, using the same constant as the record uses when it automatically goes live.  (currently set to 24 hours)

If additional changes are proposed to a historical record, before the current one goes live, the mongo tree can just be updated, and the timeout value reset to 24 hours.


Let's make sure we design this modularly, using the same time_out constant for everything.
As we may want to automatically change this to 1 week, once there are LOTS of participants, for example.
And we may want to provide the user to set the timeout to different values for camp records.

**Comment by rupalichavan9860** [comment]
I can see changes in tree now but do we need to check score also 
Because as of now can see same user support for both parent and child camp and total score of camp 1 is addition of camp 1 and camp 2 score
![image](https://user-images.githubusercontent.com/40416610/172326249-0b733b12-3b21-479b-ba37-00c221c82f93.png)

@BrentAllsop Can you please confirm

**Comment by BrentAllsop** [comment]
Yes, the canonizer service should be called with a topic num, camp num, canonizer algorithm, and as_of value.
Everything should be "as of" for that value, as it was at that date in the past, or as it will be if the in review goes live.

This concerns me that this is even possible.  The architecture shouldn't even allow this.
We should not be calculating things like this on the fly.
If this is occuring, the system is not architected, correctly.

**Comment by cd-ali-ehsan** [comment]
Hi @BrentAllsop,

Currently, the Staging environment is not using Canonizer Service since there was some work being done on the Mind Expert Algorithm. 

I think the issue has to do with the nature of the problem rather than the architecture of Canonizer. Users should not be allowed to change the parent of a camp because it violates the rules we have set for adding support. 

- Suppose User A has added support for 2 sibling camps, Camp 1 and Camp 2. 
- Camp 1 will have a score of 0.75 while Camp 2 will have a score of 0.25. 
- Now suppose another User B comes along and just change the parent of Camp 2 from Agreement to Camp 1.
- This will result in a violation of the rule that user support can only be divided at the sibling level.
- In addition to this, if try to rectify this by removing the support for User A in either Camp 1 or Camp 2, we will run into further problems: Which camp do we need to remove support from? Even if we decide on that, since User B changed the tree structure, User A is uninformed of the changes that will happen in his personal support. Basically, User B has changed the support of User A without his/her discretion.

Can you please confirm?

**Comment by rupalichavan9860** [comment]
@sajid315 This is still not working for "One Person One Vote" and "Mind Experts"

**Comment by sajid315** [comment]
@rupalichavan9860 issue reviewed and working fine now.

**Comment by rupalichavan9860** [comment]
@sajid315 This issue is working fine now 
But there are still some issues on "include review" filter and as discussed with @sajid315 and @cd-ali-ehsan  I have added separate ticket for the same #1608

**Comment by saniatg** [comment]
@rupalichavan9860 mentioned issue is working fine on production

**Comment by rupalichavan9860** [comment]
Verified
