### ISSUE TITLE
"Total Support for This Camp (including sub-camps)" is not listing supporter names correctly 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#179]
Please check following scenario:

For "Testing Topic by RN-ME1" topic "Total Support for This Camp (including sub-camps)" is not listing supporter nick name "Rupali C" .
1.For "Rupali C"  Account Settings->My Supports this topic is listed under supported camps 
2.When trying to support this camp it is displaying "Warning! You are already supporting this camp. You cant submit support again." but name is not listed in "Total Support for This Camp (including sub-camps)" panel.
Please clarify
![image](https://user-images.githubusercontent.com/40416610/42525710-7b4e8c22-8491-11e8-879f-8da3183b6a24.png)
![image](https://user-images.githubusercontent.com/40416610/42525760-9ce09e3e-8491-11e8-8441-c38bbe8fa806.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 this is not an issue. This is not coming because you have chnaged camp name from Agreement to Agreement ME and old support is for Agreement Camp, So it will not count your support in Agreement camp. For this there is validation for camp edit where you cant change name of a camp if its Agreement camp which is done but not on staging.

**Comment by rupalichavan9860** [comment]
@gautamv16 Thanks for clarification.Retested for other topics and camps.Working fine
