### ISSUE TITLE
If only supporter should go live (was: "Pas" should spell correctly in Algorithm Information->Mind Experts->Camp Statement

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#229]
Steps to reproduce : 
1. Go to http://production.canonizer.com Or https://staging.canonizer.com
2. Go to "Algorithm Information"
3. Click on "Mind Experts" from Canonizer Sorted Camp Tree
4. Observe Camp Statement

Expected Result : 

"Pas" should spell correctly.It must be "Pass"

Actual Result : 

![image](https://user-images.githubusercontent.com/40416610/43187859-4a4c95a8-9010-11e8-8401-44d423b5f538.png)

**Comment by BrentAllsop** [comment]
Nice catch.
This is a content issue, and I'm the only supporter of the camp, so I submitted a new version with the correct.

However, there was a problem.  Since I am the only supporter, when I submit a change, it should go live instantly.  So we need to get this fixed.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.This issue is fixed on Production but not on Staging.Please fix this on staging also

**Comment by rupalichavan9860** [comment]
![image](https://user-images.githubusercontent.com/40416610/43891254-7f9b1716-9be6-11e8-9181-6bbfc7d68790.png)

![image](https://user-images.githubusercontent.com/40416610/43891323-a1a549b2-9be6-11e8-97a7-1d1a7a823fdf.png)

**Comment by gautamv16** [comment]
This is just speeling, @brent or jim will fix it. Production is important
to fix as staging will be replicated with production data soon and it will
be overided and fixed. So mark it fixed.

*With Highest Regards*

*Varun Gautam*

*Software Developer*

*+91-9888-207706*

*gautamv16@gmail.com <gautamv16@gmail.com>*

*Great Minds Think Alike*

**Comment by rupalichavan9860** [comment]
@gautamv16 Okay.Closing this issue as it is fixed on production

**Comment by BrentAllsop** [comment]
@gautamv16, it looks like there are still issues with this.

Jim has been working on this on the live system.
He is the only supporter of this new camp:
https://canonizer.com/topic/193-Utopia-requires-God/4?
He has submitted 4 versions of a new statement, but non of them have gone live.
Since he is the only supporter, they all should have gone live instantly.

Also,  If there is a new statement, possibly submitted by someone other than one of the supporters, it should go live, after one week.  Currently, even though the first version of the statement is waiting to go live, the current buttons says: "Add Camp Statement".  This is incorrect, if there are any versions of the statement waiting to go live.  It should only say this if there is no history at all.
If there is any history, even if only waiting to go live, the button should say: "Manager/Edit Camp Statement", and should take you to the existing history page, not directly to the edit page.

**Comment by gautamv16** [comment]
duplicate
