### ISSUE TITLE
canonizer thread posts editor "Insert Image" pop up UI should match summernote "Insert Image" pop up UI

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#280]
Steps to reproduce :
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Click on "Camp Forum" on "Canonizer Sorted Camp Tree"
5. Click on any listed thread
6. Click on "Picture" icon on canonizer thread posts editor 
7. Observe UI for "Insert Image" pop up UI and compare it with summernote "Insert Image" pop up UI

Expected Result : 
UI should be proper."Choose File" No file chosen should be on the next line

Actual Result : 
As of now "Select from files" and "Choose File" No file chosen are displaying in one line.

![image](https://user-images.githubusercontent.com/40416610/46465471-48a55380-c7e6-11e8-85ad-a9ef77fd76c4.png)

![image](https://user-images.githubusercontent.com/40416610/46465495-5f4baa80-c7e6-11e8-881a-02f7552f96cf.png)

**Comment by akuks** [comment]
@rupalichavan9860 This is because you are checking the summernote on older version of bootstrap and in our application newer version of bootstrap is used. It wouldn't match with the older version.
https://summernote.org/getting-started/ and go to for bootstrap 4. You will find our toolbar is similar to this one.

**Comment by rupalichavan9860** [comment]
@akuks Okay.Yes our toolbar is similar to this so I am closing this issue
