### ISSUE TITLE
Object e-mail message isn't correct.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#284]
There is a link in the someone objected, e-mail with the caption: "See this link for options you can take if there are objections"

It should say when, not if like this: "See this link for options you can take when there are objections"

Also, the link incorrectly goes to the history page of the topic.  It should go to this "Dealing with Disagreements" topic agreement camp:

https://canonizer.com/topic/38/1

Finally this statement in the e-mail:
    "Include the following in that new help topic:"
was not intended for the e-mail, but to be included in the above "Dealing with Disagreements" camp, and has been included there.

So that statement, and the paragraph after it, should be removed from the e-mail.

**Comment by gautamv16** [comment]
@BrentAllsop and @rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.
I think Message should be "Your proposed change submitted for <topic | camp | statement> <topic name>:<camp name> <link to camp> has been objected by {nick_id}"
instead of "Your proposed change submitted for <topic | camp | statement> <topic name>:<camp name> <link to camp> has been objected **to** by {nick_id}"

Please read the message ,I think we need to remove "to" from message
Need to change the same in Canonizer_Emails document also

![image](https://user-images.githubusercontent.com/40416610/46941443-c1c76500-d088-11e8-92a3-5e176bbcab30.png)

Please confirm

**Comment by BrentAllsop** [comment]
@CanonizerJim 
Hmm, having the "to" sounds more correct to me than without.
But I'm not good at english.
Jim, could you review this issues on Github, and let us know if there should be a "to" in this object message?

**Comment by CanonizerJim** [comment]
Sure

**Comment by CanonizerJim** [comment]
"To" is more correct, but it's stylistically clunky. I'd recommend "{nick_id} has objected to your proposed change submitted for <topic | camp | statement> :"

**Comment by gautamv16** [comment]
@rupalichavan9860 @BrentAllsop pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and I am fine with this now.
@BrentAllsop Please test and close
