### ISSUE TITLE
I want to upload a large PDF file for people to download

### ISSUE THREAD

**Issue by CanonizerJim** [the-canonizer/canonizer.2.0#293]
I have a 47 meg PDF file that I want to make available for download on Canonizer, but I can't do that on the blog. Is there a way to host a file on Canonizer?

**Comment by BrentAllsop** [comment]
@CanonizerJim 
Yes, we can deposit it with the other images people can upload.  The White Paper is also there.
But Varun will need to do put it there, since it is larger than the allowed image upload size.
The url will be: http://canonizer.com/files/<name of pdf>

@gautamv16 
Are we keeping http access log files?
Will we be able to keep track of how many times this is downloaded by anyone in the log files?
Thanks,
Brent
