### ISSUE TITLE
Add new "Create New Camp" button under the "Create New Topic" button on topic pages..

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#314]
The user should be able to select the parent camp on the create form page, the default parent should be the agreement camp.

**Comment by gautamv16** [comment]
Need discussion on this feature. will do in next meeting

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check this feature as developed

**Comment by rupalichavan9860** [comment]
@gautamv16 I can see the newly added link "Create New Camp" under "Create New Topic" but when I click on "Create New Camp" it is redirecting to  https://staging.canonizer.com/camp/create/88/1 instead of respective topic.
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/54673029-6ad62800-4b1f-11e9-8135-42c93fe18741.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested. Now it is not redirecting to https://staging.canonizer.com/camp/create/88/1 but I have modified topic name from "Test : 14 March 2019" to "Test : 14 March 2019-2" and when I click on Create New Camp link it is displaying Old topic name 

And if I go to Manage/Edit This Topic->View This Version(latest one)->Create New Camp---I am getting page crashed
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/55054520-30700c00-5086-11e9-9ebb-bf1f731e4f67.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and page crash issue is resolved now.As this feature is developed I am closing this.
I will create a new issue for topic name display
