### ISSUE TITLE
All camp forum pages need to be camp centric, not topic centric.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#410]
When you go to the "camp forum" page for something other than the agreement page (approachable via science), it should be focused on the camp, not the topic.

For example "List of All Threads" should say: "List of all Camp Threads".

Then when you create a new thread, on that page:

instead of:
Create a new thread for Topic : Theories of Consciousness
it should say:
Create a new thread for camp: Approachable Via Science

Also, in staging, it seems like you can't create a new thread, it gives a "Data cannot be found" error message.

**Comment by akuks** [comment]
@BrentAllsop this is fixed. There might be some mail issue with the staging. In Production email is working fine when the thread created. Already checked that. 

Mail functionality is intact and is not modified in this or previous git issues. Please verify and let me know if there is any issue

**Comment by rupalichavan9860** [comment]
@akuks I have tested and looks good to me.But still I am getting following error on www.canonizer.com **"This page isn’t working canonizer.com is currently unable to handle this request.
HTTP ERROR 500"** 

![image](https://user-images.githubusercontent.com/40416610/54421196-ef950080-4731-11e9-936f-a93dc5e7e1d3.png)

This will get fixed in 9th release deployment.So I will keep this open and after 9th release I will check and update accordingly

**Comment by rupalichavan9860** [comment]
@akuks Tested and verified .
