### ISSUE TITLE
Camp Forum->My Participation is displaying multiple entries for single thread 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#426]
Steps to reproduce : 
1. Go to https://staging.canonizer.com or https://canonizer.com
2. Go to Browse and select any topic
3. Go to Camp forum
4. Create thread or go to existing thread
5. Add 3-4 replies using same username
6. Click on "My Participation" tab

Expected Result : 
My Participation should list only one entry for even if user replies multiple times in the thread

Actual Result : 
As of now "My Participation" tab is displaying same thread name multiple times(count of user reply count for single thread)
![image](https://user-images.githubusercontent.com/40416610/52717491-396db800-2fc7-11e9-8f39-2ed8092f667b.png)

**Comment by rupalichavan9860** [comment]
@akuks Retested and verified

**Comment by sonalizibtek** [comment]
This issue is again appearing :
Please find the attached screen shot 
<img width="960" alt="Screenshot (817)" src="https://user-images.githubusercontent.com/99309948/174555157-747bb2a7-4669-4915-b59e-255da1dd8a60.png">
![Screenshot (819)](https://user-images.githubusercontent.com/99309948/174555186-8ea3838a-8ed5-459b-90d0-dd1af8f579e1.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
