### ISSUE TITLE
Include "note" in the e-mail when notifying people of proposed changes.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#437]

**Comment by gautamv16** [comment]
Fixed @rupalichavan9860

**Comment by rupalichavan9860** [comment]
@gautamv16 I am not getting emails for any change in staging..I am getting submittal(topic,camp) emails only.

**Comment by gautamv16** [comment]
@rupalichavan9860 this email is for supports of topic when change made.

**Comment by gautamv16** [comment]
@rupalichavan9860 this email is for supports of topic/camp when change made.

**Comment by rupalichavan9860** [comment]
@BrentAllsop I can see the "note" in proposed change mail.But if the note is blank then email looks like below.
![image](https://user-images.githubusercontent.com/40416610/55100171-38ac6380-50e7-11e9-9ee8-16671ee611ee.png)

Can we avoid note in email if note is blank?
Do we want any change in this or is it fine?

**Comment by BrentAllsop** [comment]
Also, e-mail about statement changes say:
"Brent_Allsop has proposed a change to this statement #1519 which you currently directly support."
Should say:
"Brent_Allsop has proposed a change to the statement for camp &lt;current live camp name&gt; which you currently directly support.
All places that use a number like this, should be changed to a more informative value, like the camp name.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check this

**Comment by rupalichavan9860** [comment]
@gautamv16 I am not getting topic/camp change mails and I am getting "Thank you for contributing to Canonizer.com" mail after statement change.

@BrentAllsop Can you please check at your end.Please test and close if working for you

**Comment by BrentAllsop** [comment]
@rupalichavan9860   Are you talking about staging?
Yes, I just made a change to a topic on staging, and it went live.
That was an hour or so, ago, and I have not yet received an e-mail about that.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Yes.Staging.But I am not sure your email on staging is configured for receiving mails or not.Need to check with Varun

**Comment by gautamv16** [comment]
Only rupali email is there on staging for testing so all emails will go to her email. And only different supporter will receive emails bye cron job which is configured on production which will check for any change which are not in grace period. You can test text changes for any change which dont have grace period.

**Comment by BrentAllsop** [comment]
I have been getting some e-mails from staging, but nothing from these.

**Comment by gautamv16** [comment]
@rupalichavan9860 as discussed in meeting pls check and close.

**Comment by BrentAllsop** [comment]
I am getting emails from staging.
Not seeing "Note:" and other values that should be included in the e-mail.
We need more than just the link.
Should say something like: "You submitted a change to the "camp name" camp.

Also, supporters of the camp aren't being notified when a change is submitted.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please check email after submitting change to camp statement.
When I am submitting change to any camp statement I am getting "Thank you for contributing to Canonizer.com" mail instead of proposed change mail.

**Comment by BrentAllsop** [comment]
@gautamv16, yes, that is what I am seeing.
The "Thank you for contributing to canoinzer.com" e-mail needs to provide more information.  Like: "You submitted a change to &lt;camp name&gt;.

And supporters of the camp should also get a notification that a change has been proposed.

**Comment by BrentAllsop** [comment]
For modification see the changes to these templates:
"Thank submitter whenever new content is submitted"
and
"When you get a new delegated supporter."
in the google doc:
https://docs.google.com/document/d/1xpdJ9XHs7FgZkJth9NE4chhTBR73p9XY_iu5S6OQLYg/edit?usp=sharing

**Comment by gautamv16** [comment]
@rupalichavan9860 pls see changes done and close issue

**Comment by rupalichavan9860** [comment]
@gautamv16  @BrentAllsop I have tested this and I received following mail
![image](https://user-images.githubusercontent.com/40416610/58608623-29ea5480-82c2-11e9-8944-abba0f3a8e81.png)

But the word "statement"  is missing as per email template
![image](https://user-images.githubusercontent.com/40416610/58608774-c280d480-82c2-11e9-8aa0-7b63359cc2b9.png)

Expected Result : 
It should be "You proposed a change for **statement** Testing Namespace Funct : Test 19 may" instead of "You proposed a change for Testing Namespace Funct : Test 19 may"

**Comment by rupalichavan9860** [comment]
I have tested for delegated support mail also.
1.Topic name is missing in mail body.As of now it is displaying only camp name 
2.Subject line is displaying as "Rupali N has just delegated **their** support to you." and in body it is displaying as "Rupali N has just delegated **his** support to you in this topic: : a test camp".
It should be "their" instead of "his" as we have decided in issue #180 
Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/58621922-0e924000-82e8-11e9-83b3-d923f70b0c30.png)

**Comment by BrentAllsop** [comment]
Also, proposed change e-mails are incomplete.
They say:
"Jim Bennett has proposed a change to this statement #1573 which you currently directly support."
But the template in the google dock says:
"{nick_id} has proposed a change to this &lt;topic | camp | statement&gt; &lt;topic name&gt;:&lt;camp name&gt; &gt;link to camp with change, as_of value set to include review> which you currently directly support."
numbers like #1573 has no meaning to users, we should always use something like current: &lt;topic name&gt;:&lt;camp name&gt;.

**Comment by gautamv16** [comment]
@BrentAllsop there is no id in statement email. I think you are checking old email or email from live site.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .
I think <topic name>:<camp name> only should display in bold format.As of now the keyword "statement" also displaying in bold format
![image](https://user-images.githubusercontent.com/40416610/60499571-5ab11580-9cd6-11e9-9d9d-b1258b030672.png)

Same for camp 
![image](https://user-images.githubusercontent.com/40416610/60499500-35240c00-9cd6-11e9-944d-d1907fc6e8c9.png)

@BrentAllsop Please check and close if fine for you

**Comment by BrentAllsop** [comment]
These issues are a problem, I think both of those issues should be fixed.
We can review other e-mail formatting in a future meeting before we close this.

**Comment by gautamv16** [comment]
@BrentAllsop and @rupalichavan9860 these "camp" and "statement" are coming dynamically either all will not be bold or all will be bold. We cant make these words fix as email is using single template for everything. So as per me its not a big deal or issue to change single word bold. If you guys still want then it requires to create seperate template for topic, statement and camp. So please decide on that.

**Comment by BrentAllsop** [comment]
Let's discuss this in the next meeting.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.
The keyword "topic" in Proposed change to topic mail is displaying 2 times and according to discussion it should be "Gautam has proposed a change to this topic : Theories of Consciousness" instead of "Gautam has proposed a change to this topic topic Theories of Consciousness"

As of now ":" is missing and The keyword "topic" is displaying 2 times.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/61175046-b3ca5480-a5c6-11e9-90d7-a7e2a9d61c33.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
