### ISSUE TITLE
User supports : List of supported camps is displaying different topic name

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#516]
I have submitted support for following topics and checked user supports : List of supported camps page.and I found following mismatches
1. Help : 
Topic name is "Help" but User supports : List of supported camps is displaying "Screen Shots"

![image](https://user-images.githubusercontent.com/40416610/58761611-f4fd2c80-8563-11e9-9b1b-925267525d97.png)

![image](https://user-images.githubusercontent.com/40416610/58761617-0ba38380-8564-11e9-9065-4d48bf12c90d.png)

2. Theories of Consciousness
![image](https://user-images.githubusercontent.com/40416610/58761820-a781bf00-8565-11e9-9d84-7672d2b28f4e.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 after all investigation for this. The thing you are mentioning is not topic name. This support tree showing camp name not topic so you are comparing it with topic history change so that is not true. All this is camp tree and camp name are coming here. If there is child then agreement camp tree will show all child camps and if there is no child then only main camp title will display.

**Comment by rupalichavan9860** [comment]
@gautamv16 Okay.But is there any way to change the camp name? otherwise user will get confused because if user goes to topic history or camp history he/she is not able to see the respective name displaying under list of supported camps.

**Comment by gautamv16** [comment]
@rupalichavan9860 user must go from here to camp history not to topic history..

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
