### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ';'

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#599]
Please refer attached screenshot for errors
Pre-condition : User is not logged in

![image](https://user-images.githubusercontent.com/40416610/77071542-3dfa7080-6a12-11ea-850a-894d77ced88b.png)

Pre-condition : User is logged in

![image](https://user-images.githubusercontent.com/40416610/77071652-70a46900-6a12-11ea-8f5c-9b9d2af01e8b.png)

**Comment by BrentAllsop** [comment]
We shouldn't release the 17th release, unless this is fixed.
I thought this was fixed, on staging?

**Comment by rupalichavan9860** [comment]
@BrentAllsop Yes I just checked and I am not seeing issue "Uncaught SyntaxError: Unexpected token ';'"
But still I can see "GET http://www.politicit.com/img/politicit_logo.png 404 (Not Found)"

Is this an issue?If no I am okay to close this issue

**Comment by gautamv16** [comment]
@rupalichavan9860 , @BrentAllsop , the issue with this 
 http://www.politicit.com/img/politicit_logo.png is that this image is being used in the statement of this very camp. But the logo image has been removed from the original site ie from  http://www.politicit.com site. so it is not loading and hence canonizer shows this error in console, it can be fixed by editing the statement and entering the correct url for the logo image
the new logo url for this site is something like this that i have checked
http://politicit.boxstergts.net/wp-content/uploads/2014/01/politicit_logo_onwhite.png

**Comment by BrentAllsop** [comment]
Sorry for the confusion, I thought this was a different error.
But it is nice to have this one fixed, also.
