### ISSUE TITLE
List on the Canonizer Main Page should be sorted

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#602]
List on the Canonizer Main Page(Canonized list for) should be sorted, according to the selected canonizer algorithm.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.When I am selecting algorithm "Mind Experts" it is taking time to load the page and after page load I can see page like below.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/90260478-2a402280-de69-11ea-8652-0d970088186f.png)

Is anyone facing this issue?

**Comment by gautamv16** [comment]
@rupalichavan9860 , fixed it can you check it again

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .I can see the page properly but still page load time is almost 3 mins.
@BrentAllsop Is it fine?Can you please check and confirm

**Comment by BrentAllsop** [comment]
Seems workable to me, at least for now.
There is another issue dealing with pagination (rather than displaying all topics) which I believe will help with the performance.
https://github.com/the-canonizer/canonizer.2.0/issues/594
I referenced this performance in that issue, to make sure the performance is adequately fixed (or cashing of some kind is used) on this one, before closing that one.
