### ISSUE TITLE
Add most recent post date column in the forum threads page.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#653]
There are currently only two values or columns, in thread tables:
https://canonizer.com/forum/88-Theories-of-Consciousness/6/threads

Change this to a table with a header.
In the 1 reply column, move the word 'Replies' to only exist in the header, and only have the number in the row.

Add an additional column for "Most Recent Post Date", and include that date in the column of each row.

And add "Thread Name" to the column with the threads in it.

**Comment by BrentAllsop** [comment]
And while we're at it, let's add a "bread crumbs" link on the threads page, the same as the one on the "All Threads" page.
So all these are links back to the camps:
Camp: Agreement / Approachable Via Science / Representational Qualia

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. I can see all the changes now but "bread crumbs" font size is not uniform with others. Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/97898077-6181e980-1d5d-11eb-9e39-351ec836d547.png)

![image](https://user-images.githubusercontent.com/40416610/97898127-72325f80-1d5d-11eb-8352-e263bbdef99a.png)

Also I can see date in "Most Recent Post Date" but on thread page I can see like "Thread Post at 8 years ago" 
Can we put exact date here also instead on "8 years ago"?
@BrentAllsop Please confirm

**Comment by gautamv16** [comment]
@rupalichavan9860 changed "Can we put exact date here also instead on "8 years ago"?" this to display date and also fixed issue for font change

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop I think yes. Every post should display exact date instead of "replied 2 years ago". Please confirm
Also most recent post date column is displaying thread created date instead of most recent post date. Please refer following topic 

https://staging.canonizer.com/forum/189-Testing-flow1-1/1-Agreement/threads
Thread name : Testing
Thread is created 2 years ago

![image](https://user-images.githubusercontent.com/40416610/98472142-0e091300-2217-11eb-8177-257d7ad21587.png)

And latest post is 1year ago by user nickname "Ash"

![image](https://user-images.githubusercontent.com/40416610/98472153-29741e00-2217-11eb-8085-77263c5ce286.png)

And Most Recent Post Date is displaying is 2 years ago date(23-08-2018)

![image](https://user-images.githubusercontent.com/40416610/98472166-414ba200-2217-11eb-8328-7fdddfae2b34.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. I can see the correct Most Recent Post Date in column and date in post instead of like "2 years ago". But on List of All Camp Threads page , I can see pagination on the top instead on bottom(Previously it was on bottom)

It should be on bottom

Staging : 
![image](https://user-images.githubusercontent.com/40416610/99909410-5db70680-2d0e-11eb-9606-867e92a76984.png)

Live : 
![image](https://user-images.githubusercontent.com/40416610/99909391-411ace80-2d0e-11eb-84c3-b0456719a93d.png)

@BrentAllsop Can you please check and confirm?

**Comment by gautamv16** [comment]
@rupalichavan9860 moved the pagination to bottom of table. pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
@BrentAllsop Can you please check and close if fine for you

**Comment by BrentAllsop** [comment]
Yes, looks nice so closing this one.

**Comment by rupalichavan9860** [comment]
@gautamv16 As per discussed in meeting need following change on thread post page so reopening this issue 

![image](https://user-images.githubusercontent.com/40416610/100564439-0fde6780-32e7-11eb-9a72-acb2fc253321.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 I have checked this and found that this is displaying the thread created date but i guess some time ago it was the functionality to update the dates in threads when you post any comment on it. but for new data it will come fine. you can test it by creating new threads. i can show the date of the first post (or reply) but it will contradict in case there is not reply when the thread was created

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. But can you please change the statement to "Thread **Created** at 28-01-2019 by Ash" instead of "Thread **Post** at 28-01-2019 by Ash" as we are displaying thread created date here.
![image](https://user-images.githubusercontent.com/40416610/101307699-154f2b00-386e-11eb-9250-24440d8df4ab.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Looks fine now so closing this issue
