### ISSUE TITLE
Page Crash On Live System While Creating New Account

### ISSUE THREAD

**Issue by kellycasa1** [the-canonizer/canonizer.2.0#684]
<img width="1280" alt="Screen Shot 2021-02-17 at 10 16 24 AM" src="https://user-images.githubusercontent.com/79217857/108241617-43bc7280-7109-11eb-84f9-769fed8a1cca.png">

Registered new account and received this fatal error when submitted

**Comment by BrentAllsop** [comment]
This person was able to create his account, so closing this.

**Comment by BrentAllsop** [comment]
We need to create the ability to handle whenever any API, not owned by us, fails.
So it reports to the user, it isn't a canonizer issue, it is an API issue.
In the error message, report the api, and the issue.

If possible we should review other API failure cases, to be sure they are handled intelligently.
possible ones to review:

In fact, handle all errors, intelligently, so we see a canonizer error page, instead of this kind of crash.

**Comment by gautamv16** [comment]
@BrentAllsop I have added custom error message to this if somehow system is not able to send the email it will not crash the site instead it will redirect to the previous page and show alert error that system is not able to send email due to some reason.
