### ISSUE TITLE
Add "Jobs" and "Services" links on the side bar.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#706]
Add two more links, under "Blog"  on the side bar:

Jobs:         https://canonizer.com/topic/6-Canonizer-Jobs/1-Agreement

Services:    https://canonizer.com/topic/37-Canonizer-Services/1-Agreement

**Comment by rupalichavan9860** [comment]
@gautamv16 I can see Jobs and Services links under "Blog" on the side bar but as of now they are redirecting to incorrect page 
This may be because  https://canonizer.com/topic/6-Canonizer-Jobs/1-Agreement and https://canonizer.com/topic/37-Canonizer-Services/1-Agreement are not present on staging

So I will keep this open and will close after testing it on production environment

**Comment by BrentAllsop** [comment]
Yes, these only exist in production.
Can we do an update of the staging data?
Then we can close this before release.

**Comment by rupalichavan9860** [comment]
@BrentAllsop I can see links are redirecting to correct pages now on new secure server. Should I close or this should exists on staging also?

**Comment by rupalichavan9860** [comment]
@gautamv16 Working fine on live so closing this
