### ISSUE TITLE
http://3.12.165.249/ : Data Could Not Be Found issue

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#723]
Steps to reproduce : 
1. Go to http://3.12.165.249/
2. Login with valid email and password
3. Click on White Paper link from left menu

Expected Result : 
It should display White Paper pdf in new window

Actual Result : 
It is displaying "Oops! Data Could Not Be Found" .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/123674353-263da900-d85f-11eb-9304-04e192b5ce4b.png)

**Comment by BrentAllsop** [comment]
This is a general problem for all files in the files directory.
To fix this, we need to have a way to duplicate all data, like this, on a test, or any other server, from production.

And we'll need to monitor the switch of IP addresses, so that nobody deposits a new file on the old system, and the time the data is duplicated on the new IP system.
so no files are lost.

**Comment by rupalichavan9860** [comment]
Found same issue when trying to open uploaded file on File Upload page

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. I can see the White Paper pdf in new window so closing this issue
