### ISSUE TITLE
Camp name is not displaying under delegated supported camp lists

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#749]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to any topic : ref topic -https://staging.canonizer.com/topic/324-Testing-issue-743/1-Agreement
4. "Rupali C" created "Test camp 1" and "1rupali1" is delegating support to "Rupali C"
5. When "Rupali C" created "Test camp 2" and supporting "Test camp 2" , "1rupali1" is automatically added as a delegated supporter but this support is not listing on user supports page and supported camps page
 please refer attached screenshots for more details

![image](https://user-images.githubusercontent.com/40416610/131721745-ccc0e392-658c-4800-9539-f55cdc80a4ad.png)

![image](https://user-images.githubusercontent.com/40416610/131721948-d019f02e-2414-4a82-8c70-84ba5a39c691.png)

![image](https://user-images.githubusercontent.com/40416610/131722029-4bf8f151-9e67-4e4b-80c8-d86fd3425929.png)

**Comment by rohit-talentelgia** [comment]
@rupalichavan9860 

We are reviewing this issue, but the reference link is throwing an error:

https://staging.canonizer.com/topic/324-Testing-issue-743/1-Agreement
 
![image](https://user-images.githubusercontent.com/8575740/134857548-3f5fbdda-5c0e-43e4-88a7-3cbd58683aaa.png)

**Comment by rupalichavan9860** [comment]
@rohit-talentelgia @saniatg Please follow below steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create a new topic and create 2 new camps and support both camps using same user
4. Logout and login with another user
5. Delegate their support to both camps(Now user can see both camps in supported camp list)
6. Logout and login with first user again
7. Create 3rd camp and support that camp(it will automatically add delegated support of previous user but 3rd camp name is not listing under supported camps)

**Comment by rupalichavan9860** [comment]
Found one more issue on this 
When first user created 3rd camp , delegated support is getting added automatically but incorrect choice number for delegated support is getting displayed

![image](https://user-images.githubusercontent.com/40416610/134876657-805f37c7-180f-41a3-8ec2-6557bc5f3ce0.png)

**Comment by nalwa** [comment]
Hello @rupalichavan9860 @gautamv16 

We have reviewed this ticket in detail and found the issue as to why is this happening. 

1. User 1 create a topic "Topic abc" and  camp "subcamp 1" and give support to this subcamp.
2. User 2 logs in and delegates the support to "subcamp 1", at this when this user delegates support the first time, the entry is added to the database. 
3. If User 1 creates a new camp under same topic ans support it , then no entry goes into the database for the delegated support and is only calculated based on the previous delegated support. And this is the reason as why this is not appearing under MY SUPPORT CAMP for USER 2 .

@gautam, we need to discuss as why it is done in this way and should we update the code so that the delegate support values are saved in database in case a camp is created under a delegated support camp/topic

**Comment by nalwa** [comment]
@rupalichavan9860  @gautamv16 issue fixed.

**Comment by rupalichavan9860** [comment]
@nalwa @gautamv16 Tested .Still facing issue for choice/preference no when reordering the camps while supporting latest camp. Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/135671807-ce57426c-74f9-4bb4-9227-8032fa4eec76.png)

**Comment by rupalichavan9860** [comment]
@nalwa Also check choice numbers on supported camps page

![image](https://user-images.githubusercontent.com/40416610/135673563-feb22de8-8051-47cf-ba0e-6c516919f545.png)

**Comment by nalwa** [comment]
@rupalichavan9860  if this issue is coming in case of  reordering the camps then  it is a different task. I reviewed the code for re-ordering and  my findings:
**On support re-order delegate support re-order code is not there.**
So i would suggest please create a different ticket for re-ordering issue. As this ticket was not related to re-ordering.
Thanks

**Comment by rupalichavan9860** [comment]
@nalwa I had a discussion on this with @BrentAllsop and he said we need to fix this in this ticket only

**Comment by nalwa** [comment]
@rupalichavan9860  i will work on it

**Comment by nalwa** [comment]
@rupalichavan9860 Following fixes made  with II Part of this ticket:

1. When reordering the camps while supporting Choice/preference no is fixed both on **support tree** and **under support camp list of delegated supported**
2. When any direct supporter go to their **support camp list** in account setting and re-order camps  for any topic in that case delegate supporters preference was not getting changed as per the person who he has delegated his/her support .
(Code was not written this)
This was not mentioned but i found it so i fixed it here.

Please let me know if anything done wrong here.

**Comment by rupalichavan9860** [comment]
@nalwa Tested and working fine
