### ISSUE TITLE
Make actions you can't do visible (just greyed out) so people can realize they need to take an action to do them.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#756]
After submitting any change to topic/camp/statement when another user added their support to the camp ,user is not able to see object button as per functionality 

As per discussed in meeting we should have object button with disabled mode for those users and also we should have some note or tooltip on object button hover

**Comment by BrentAllsop** [comment]
Thank you, Rupali, for getting this started.  the object button is one example.
Another is the create new thread, and post, in the forums.  These buttons aren't there, when you are not logged in.
You should be able to see them, when not logged in, so people can realize they need to be logged in, to make posts.

**Comment by nalwa** [comment]
Hello @BrentAllsop  I am working on this ticket and  it will take around 8 hrs to complete it.

**Comment by nalwa** [comment]
@gautamv16 I have completed the ticket and created PR for same, please merge and make it available for testing.

@rupalichavan9860  Points covered related to Forum are:
1. For Non-logged in user "Create Thread" button has been displayed. (As mention by @BrentAllsop )
2. For non-logged in user when there is no thread under form it was display button "All Thread" and table header as in below screenshot
![image](https://user-images.githubusercontent.com/4891200/134883439-b8cb81b5-c877-42b2-8744-170ed0920515.png)

which actually makes no sense here, so i removed them and make it look like as in below: 
![image](https://user-images.githubusercontent.com/4891200/134883763-bc46e9f5-6f07-4ff0-9d83-7775f3586374.png)


Points Covered for Topic/Camp/ Statements are:
1. **Disabled object Button** will be displayed on history page of topic/camp/statement for users who are not supporting it with message on info icon - "Only Supporter have access to object this topic/camp/statement ".
2. **Disabled object button** will appear on  history page of topic/camp/statement for users who have supported topic/camp/statement after  submitting any change to it with message - "You can not object this camp statement because you supported this camp after updation was submitted".

@gautamv16  @BrentAllsop  Please provide the message text for above two cases. i will update that.

**Comment by rupalichavan9860** [comment]
@nalwa Tested. 
Need minor change in tooltip 

Camp History : 
It should be "Only **supporter** have access to object the camp." instead of "Only **supported** have access to object the camp."
Topic History : 
It should be "Only **supporter** have access to object the topic." instead of "Only **supported** have access to object the topic."
Statement History :  
It should be "Only **supporter** of this camp has access to object." instead of "Only **supported** of this camp has access to object."

**Comment by BrentAllsop** [comment]
@rupalichavan9860 and @CanonizerJim, we need to find some way to improve all these tool tips.
Perhaps a meeting, where we walk though all the cases?

**Comment by BrentAllsop** [comment]
Kshipra, Iffort needs to be included on any meetings/discussion, along with Jim.

**Comment by sunnyjindal** [comment]
The Object button as shown now will be grayed out.

The tooltip will just say: You cannot object to this camp statement.

When a user tries to click it, it will show a popup with the following message. 

To object to this camp statement, you should be a direct supporter of the camp and should have supported it before the statement was submitted. For more information about disagreement, please read here: https://canonizer.com/statement/history/132-Help/4-Dealing-with-Disagreement

@nalwa @BrentAllsop @dakshiffort

**Comment by nalwa** [comment]
@rupalichavan9860  @sunnyjindal  @BrentAllsop 
I have update the content as well implemented popup as described above.
please check below screenshot for popup layout:
![disagreement_popup](https://user-images.githubusercontent.com/4891200/144041982-1658d2e8-3aec-4bd9-adf3-1fd50ef56826.png)

**Comment by sunnyjindal** [comment]
@nalwa can we have the text like this? You can make Disagreements as the link below:
---------------------

To object to this camp statement, you should be a direct supporter of the camp and should have supported it before the statement was submitted. 

For more information about disagreement, please read topic: <Disagreement>

**Comment by nalwa** [comment]
@sunnyjindal  okay will update it

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
@BrentAllsop I have 1 doubt here, why it should redirect to history page of Disagreement?

I think it should redirect to https://canonizer.com/topic/132-Help/4-Disagreement

**Comment by rupalichavan9860** [comment]
@sunnyjindal Can you please check this?

**Comment by sunnyjindal** [comment]
@rupalichavan9860 @nalwa that's correct. It should go to: https://canonizer.com/topic/132-Help/4-Disagreement

**Comment by rupalichavan9860** [comment]
Thanks @sunnyjindal 
Moving this to "To do"

**Comment by nalwa** [comment]
@rupalichavan9860 @sunnyjindal  i will update the link.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
