### ISSUE TITLE
Getting page crash on history pages

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#804]
Pre- condition :  User is not logged in 

Topic : https://staging.canonizer.com/topic/315-Test-topic-6-oct-2021/2-test-camp-1-updated-by-r-cano#statement

Steps : 
Click on "Manage/Edit Camp Statement"

Screenshot : 
![image](https://user-images.githubusercontent.com/40416610/136200548-2d412c1b-0008-4e0c-ae62-77190931975c.png)

Note :  Getting on some specific scenario , Will add steps later

**Comment by nalwa** [comment]
@sunnyjindal  @kshitij1326 @rupalichavan9860  This issue  arises because of conflict in **Pull Request #798 from the-canonizer/CodeDistrict**  (Mentioned in yesterday meeting as well - THU, 7th cot 21)

This  work was  from my side which is lost / incomplete on staging now. I will update my lost work on staging.
Thanks.

**Comment by rupalichavan9860** [comment]
@nalwa @gautamv16 Tested and verified by me and @saniatg . It is working fine now so closing this
