### ISSUE TITLE
Need option to re-verify account for user while login/forgot password.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#865]
As of now even if user has not verified their account , user is able to reset password 
So we need option to re-verify account

**Comment by ashish76** [comment]
#865 this has been implemented and pushed on the server. 

A user can click on the Forgot Password, if a user account is not verified then the system will show an error message with a link to request for verification code. Users can click that link to request for new verification code to activate the account.

**Comment by sunitamary** [comment]
what ever the issue is mentioned is working fine, unverified user has been validated telling his/her account has been not verified while trying with forgot password.But when an unverified user tries to logging the validation error message is shows twice. Please refer the below screenshot.,
![Screenshot from 2021-11-18 11-55-03](https://user-images.githubusercontent.com/92773405/142363866-ae2e43e1-6431-4808-a347-a2c4061f6ae1.png)

**Comment by rupalichavan9860** [comment]
Tested and verified. But there is page crash on verification page so added new issue #935

**Comment by sunitamary** [comment]
Verified on production by Bazeer. @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
