### ISSUE TITLE
If password doesn't matches it clears entered "Password" and "Confirm Password".It should not clear and cursor should focus on Confirm Password text box

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#95]
1. Go to https://staging.canonizer.com/    
2. Enter valid data in all fields    
3. Enter different password in Confirm Password text box than Password
4.Click on "Create you account" button.

Expected Result: 
It should not clear "Password" and "Confirm Password" text box and cursor should focus on Confirm Password text box

**Comment by gautamv16** [comment]
This is not an issue.. whenever password and confirm password doesn't match these are cleared because 1. User have entered wrong password mistakenly in either of these two .. So we cant guess which one may be this.
2. we can't set cursor to these fields because there may be any other field giving validation error so its not correct to set cursor to these either of these fields.

**Comment by gautamv16** [comment]
@rupalichavan9860 not an issue.
