### ISSUE TITLE
Oops! Data Could Not Be Found on privacy policy and term service click on "https://canonizer.com/videos/consciousness/"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#955]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/143992249-bbfbb8b0-132b-4c89-83d4-f5f64f84c378.png)

![image](https://user-images.githubusercontent.com/40416610/143992280-bf73df49-09ee-4322-9ce7-e8f98556def6.png)

**Comment by HamzaBinMansoor** [comment]
@rupalichavan9860 
the codebase for canonizer-video is made on core HTML CSS, footer for this page is copied from laravel code due to which it is unable to find **url('privacypolicy')** and **url('termservice')** these dynamic routes.

I think we need to replace them with:
1. https://canonizer.com/privacypolicy
2. https://canonizer.com/termservice

are these links ok?

**Comment by rupalichavan9860** [comment]
Tested and verified
